---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service-app
spec:
  selector:
    app: demo-service-app
    tier: apps
  type: NodePort
  ports:
    - port: 12801            #container port
      targetPort: 12801          #Pod port
      nodePort: 32126    #f type is NodePort then use nodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  namespace: app
  labels:
    app: erp-bs-wa-fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-app
      tier: apps
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: demo-service-app
        tier: apps
      name: demo-service
    spec:
      containers:
        - image: demo-service
          name: demo-service-container
          imagePullPolicy: Always